import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const users = [
  { "email": "nchinhtung@gmail.com", "role": "user" },
  { "email": "maianhmanhh@gmail.com", "role": "user" },
  { "email": "thylien.thapbaspa@gmail.com", "role": "user" },
  { "email": "huynhngocnhu810@gmail.com", "role": "user" },
  { "email": "anhnguyen.31231025450@st.ueh.edu.vn", "role": "user" },
  { "email": "tongtranthieu@gmail.com", "role": "user" },
  { "email": "huyntn2005@gmail.com", "role": "user" },
  { "email": "nguyentuanh8297@gmail.com", "role": "user" },
  { "email": "minhthuy5553@gmail.com", "role": "user" },
  { "email": "phuonganhlehuu5@gmail.com", "role": "user" },
  { "email": "hoangkimphan2812@gmail.com", "role": "user" },
  { "email": "nvthung0509@gmail.com", "role": "user" },
  { "email": "dinhtienminh@ueh.edu.vn", "role": "user" },
  { "email": "Chauu125@gmail.com", "role": "user" },
  { "email": "Maithanhchaukatie@gmail.com", "role": "user" },
  { "email": "Maithanhchau373@gmail.com", "role": "user" },
  { "email": "Chaumai.31231021504@st.ueh.edu.vn", "role": "user" },
  { "email": "Icecream0201@gmail.com", "role": "user" },
  { "email": "Hanguyen11@gmail.com", "role": "user" },
  { "email": "Tatdat1807@gmail.com", "role": "user" },
  { "email": "Nhanha332@gmail.com", "role": "user" },
  { "email": "Shirozzz@gmail.com", "role": "user" },
  { "email": "youareinall@gmail.com", "role": "user" },
  { "email": "Dat877@gmail.com", "role": "user" },
  { "email": "Annn323@gmail.com", "role": "user" },
  { "email": "ngohan2705@gmail.com", "role": "user" },
  { "email": "vinhtrinh.31221022962@st.ueh.edu.vn", "role": "user" },
  { "email": "locnguyen.31221021931@st.ueh.edu.vn", "role": "user" },
  { "email": "ryuhelios273@gmail.com", "role": "user" },
  { "email": "nguyenphuctue2107@gmail.com", "role": "user" },
  { "email": "nobita070804@gmail.com", "role": "user" },
  { "email": "ttdat273@gmail.com", "role": "user" },
  { "email": "mythanhhuynh1972@gmail.com", "role": "user" },
  { "email": "tuyenpham.31221025618@st.ueh.edu.vn", "role": "user" },
  { "email": "thanhtienst2004@gmail.com", "role": "user" },
  { "email": "datb2203499@student.ctu.edu.vn", "role": "user" },
  { "email": "lethanhphuc2483@gmail.com", "role": "user" },
  { "email": "antruc1211@gmail.com", "role": "user" },
  { "email": "tienlucc06@gmail.com", "role": "user" },
  { "email": "thanhthanh21122006@gmail.com", "role": "user" },
  { "email": "minhtriet3006@gmail.com", "role": "user" },
  { "email": "qduonganhanh@gmail.com", "role": "user" },
  { "email": "nhanguyen.31241025242@st.ueh.edu.vn", "role": "user" },
  { "email": "nhantrinh.31241023606@st.ueh.edu.vn", "role": "user" },
  { "email": "khavo.31241024754@st.ueh.edu.vn", "role": "user" },
  { "email": "thunguyen.31241023597@st.ueh.edu.vn", "role": "user" },
  { "email": "nockhanh08012005@gmail.com", "role": "user" },
  { "email": "binhnguyen.31241024682@st.ueh.edu.vn", "role": "user" },
  { "email": "hantran.31231021421@st.ueh.edu.vn", "role": "user" },
  { "email": "nguyenvo.31241028106@st.ueh.edu.vn", "role": "user" },
  { "email": "adorablejinhami@gmail.com", "role": "user" },
  { "email": "gh296094@gmail.com", "role": "user" },
  { "email": "binhbinhthanhnguyen123@gmail.com", "role": "user" },
  { "email": "dangtrananhthu12a3@gmail.com", "role": "user" },
  { "email": "uyenluu.31231024443@st.ueh.edu", "role": "user" },
  { "email": "phuongquyng124@gmail.com", "role": "user" },
  { "email": "hanhuynh.cmo@gmail.com", "role": "user" },
  { "email": "nhucute05@gmail.com", "role": "user" },
  { "email": "august20.me@gmail.com", "role": "user" },
  { "email": "huynhnhathuyst123@gmail.com", "role": "user" },
  { "email": "nguyenthisonlan01.st@gmail.com", "role": "user" },
  { "email": "huynhhaidmst@gmail.com", "role": "user" },
  { "email": "anhngstg2801@gmail.com", "role": "user" },
  { "email": "ngochuynh.31231024413@st.ueh.edu.vn", "role": "user" },
  { "email": "mailinh.huyhoang412@gmail.com", "role": "user" },
  { "email": "anhtu107@gmail.com", "role": "user" },
  { "email": "hv190193@gmail.com", "role": "user" },
  { "email": "8.thienthancuatoi.8@gmail.com", "role": "user" },
  { "email": "ltv.tuananit@gmail.com", "role": "user" },
  { "email": "thaonhipx@gmail.com", "role": "user" },
  { "email": "letientp@gmail.com", "role": "user" },
  { "email": "kinhcan24@gmail.com", "role": "user" },
  { "email": "vietnamarch.ltd@gmail.com", "role": "user" },
  { "email": "tanbomarketing@gmail.com", "role": "user" },
  { "email": "datmoirealty@gmail.com", "role": "user" },
  { "email": "vuhonghai490@gmail.com", "role": "user" },
  { "email": "tuannguyentravel.com@gmail.com", "role": "user" },
  { "email": "huantich404@gmail.com", "role": "user" },
  { "email": "vaaythoomcum234567@gmail.com", "role": "user" },
  { "email": "thinhien326@gmail.com", "role": "user" },
  { "email": "thanhthat22@gmail.com", "role": "user" },
  { "email": "quockhai36@gmail.com", "role": "user" },
  { "email": "huynhvan22@gmail.com", "role": "user" },
  { "email": "tuanvu14@gmail.com", "role": "user" },
  { "email": "baongoc32@gmail.com", "role": "user" },
  { "email": "anhngoc@gmail.com", "role": "user" },
  { "email": "tonuwxa@gmail.com", "role": "user" },
  { "email": "tuankhang 19@gmail.com", "role": "user" },
  { "email": "jaynie.alexya8888@gmail.com", "role": "user" },
  { "email": "thanhtan12@gmail.com", "role": "user" },
  { "email": "luongvanthanh@gmail.com", "role": "user" },
  { "email": "kimkhanh292525@gmail.com", "role": "user" },
  { "email": "huynhthuthuy24425@gmail.com", "role": "user" },
  { "email": "in013047@gmail.com", "role": "user" },
  { "email": "vns.thnh02@gmail.com", "role": "user" },
  { "email": "thanhdangchoi@gmail.com", "role": "user" },
  { "email": "thaotran2003bt@gmail.com", "role": "user" },
  { "email": "baohan210305@gmail.com", "role": "user" },
  { "email": "vibt27092003@gmail.com", "role": "user" },
  { "email": "phuongpham29112005@gmail.com", "role": "user" },
  { "email": "neyu0907@gmail.com", "role": "user" },
  { "email": "nlanh2005@gmail.com", "role": "user" },
  { "email": "tonyphan22330088@gmail.com", "role": "user" },
  { "email": "phucnguyen.31241022636@st.ueh.edu.vn", "role": "user" },
  { "email": "hungvo.31231020183@st.ueh.edu.vn", "role": "user" },
  { "email": "hieunguyen.31221024179@student.ueh.edu.vn", "role": "user" },
  { "email": "tranuy1919@gmail.com", "role": "user" },
  { "email": "letien2632k3@gmail.com", "role": "user" },
  { "email": "nguyenngochuy593@gmail.com", "role": "user" },
  { "email": "nguyendaihung22650621@gmail.com", "role": "user" },
  { "email": "vile.31241025391@st.ueh.edu.vn", "role": "user" },
  { "email": "phantrungtrucdx@gmail.com", "role": "user" },
  { "email": "oanhdang.31241027058@st.ueh.edu.vn", "role": "user" },
  { "email": "lengoctuyen0103@gmail.com", "role": "user" },
  { "email": "datnguyen.31241025560@st.ueh.edu.vn", "role": "user" }
]

async function main() {
  for (const user of users) {
    const created = await prisma.profile.upsert({
      where: { email: user.email },
      update: {},
      create: {
        email: user.email,
        role: user.role,
      },
    });
    console.log(`✅ ${created.email} (${created.role})`);
  }
  console.log("Done.");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
